[package]
name = "revmapi"
version = "0.1.0"
publish = false
description = "Reth Revm Engine"
repository = "https://github.com/rethmint/revm-api"
exclude = [".gitignore"]

edition = { workspace = true }
rust-version = { workspace = true }

# the example is to allow us to compile a muslc static lib with the same codebase as we compile the
# normal dynamic libs (best workaround I could find to override crate-type on the command line)
[[example]]
name = "movevmstatic"
path = "src/examples/movevmstatic.rs"
crate-type = ["staticlib"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
serde = []
# This feature requires Rust nightly because it depends on the unstable backtrace feature.
backtraces = []

[dependencies]
errno = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true }
thiserror= { workspace = true }
revm-primitives = { path = "../crates/primitives", version = "9.0.1", default-features = false }
revm = { path = "../crates/revm", version = "14.0.1", default-features = false }
alloy-primitives = { version = "0.8.2", default-features = false, features = [
	"rlp",
] }

[build-dependencies]
cbindgen = { workspace = true }
