[package]
name = "flatbuffer_types"
version = "0.0.1"
publish = false
description = "Reth Revm Engine Api Type"
repository = "https://github.com/rethmint/revm-api"

edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
flatbuffers={workspace=true}
