name: Commit Shared Library

on:
  pull_request:
    types:
      - closed

jobs:
  commit:
    if: github.event.pull_request.merged == true
    name: Commit shared libraries
    needs: [build-linux-glibc, build-macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
      - name: Get linux-glibc artifacts
        uses: actions/download-artifact@v4
        with:
          name: librevmapi-linux-glibc
          path: api

      - name: Get macos artifacts
        uses: actions/download-artifact@v4
        with:
          name: librevmapi-macos
          path: api

      - name: Commit shared libraries
        uses: EndBug/add-and-commit@v9
        with:
          add: '["api/librevmapi.dylib", "api/librevmapi.aarch64.so", "api/librevmapi.x86_64.so" ]'
          default_author: github_actions
          message: "update shared libraries"
