name: Setup and Lint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.rs"
  push:
    branches:
      - main
    paths:
      - "**.rs"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: setup install rust and llvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make free space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install LLVM 18
        run: |
          echo "Installing LLVM 18 on Ubuntu"
          sudo apt-get update
          sudo apt-get install -y lsb-release wget software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

      - name: Set LLVM_SYS_180_PREFIX
        run: |
          prefix=$(llvm-config-18 --prefix)
          echo "LLVM_SYS_180_PREFIX=$prefix" >> $GITHUB_ENV

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.81.0
          override: true
          components: rustfmt, clippy

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install Protobuf Compiler
        run: sudo apt-get install -y protobuf-compiler
      
      - name: Set PROTOC environment variable
        run: echo "PROTOC=/usr/bin/protoc" >> $GITHUB_ENV
        
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-
      
      - name: Clippy
        run: cargo clippy --workspace --all-targets
        env:
          RUSTFLAGS: -Dwarnings

    
